version: 2
jobs:
  build:
    branches:
      only:
        - test-ci
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm run test
      - run: npm run build