version: 2
jobs:
  build:
    branches:
      only:
        - test-ci
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
        keys:
          - npmcache-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
        key: npmcache-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
      - run: npm run build
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run: npm run test
workflows:
  version: 2
  build-test:
    jobs:
      - build:
        filters:
          branches:
            only: test-ci
