version: 2
jobs:
  build:
    branches:
      only:
        - test-ci
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm i
      - run: npm run build
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
