version: 2
jobs:
  install:
    working_directory: ~/deploy-ui
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npmcache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependance
          command: npm i
      - save_cache:
          key: npmcache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run:
          name: Build
          command: npm run build
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - run:
          name: Test
          command: npm run test
workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only: test-ci
          requires:
            - install
      - test:
          filters:
            branches:
              only: test-ci
          requires:
            - install
