version: 2
jobs:
  build:
    working_directory: ~/deploy-ui
    branches:
      only:
        - test-ci
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
        keys:
          - npmcache-{{ checksum "package-lock.json" }}
      - run:
        name: Install dependance
        command: npm i
      - save_cache:
        key: npmcache-{{ checksum "package-lock.json" }}
        paths:
          - node_modules
      - run:
        name: Build
        command: npm run build
      - run:
        name: Test
        command: npm run test
